### ISSUE TITLE
Supplied Software definition requires clarification (David Rudin)

### ISSUE THREAD

**Issue by MarkGisi** [OpenChain-Project/License-Compliance-Specification#11]
Supplied   Software.  Supplied Software is defined as "software that an   organization *delivers* to third parties...."  It's not clear why   "delivers" is the trigger here.  Shouldn't the trigger for   Supplied Software be based an action that requires a   compliance-related action under the OSS license?  For example, if I   "deliver" MIT code via a cloud service I am not incurring any   compliance obligations, yet it could still be considered Supplied Software   under this definition
--

**Comment by MarkGisi** [comment]
I don't see the current use of "delivers" inconsistent with delivering MIT licensed software via the cloud. In that situation the delivery of the software does not trigger any MIT obligations where AGPL license software it may. That is, the MIT obligations are zero. Or the compliance artifacts is represented by the empty set. 

But if there was still a better term than "delivers" we should consider it. We will discuss it at the next spec working group meeting.

**Comment by MarkGisi** [comment]
The Feb 18th working group decided to consider updating the Supplied Software by replacing the word "delivers" with "distributes". The new proposed definition is:

Supplied Software - software that an organization distributes to third parties (e.g., other organizations or individuals).

We will seek additional feedback.

**Comment by JimHutchison** [comment]
There are many Open Source licenses.  Applying specific Open Source license _terms_ to the interpretation of the OpenChain specification creates a spec dependency on the interpretation of each such license.  Would the spec benefit from a clarification that it, does not define license terms?

**Comment by MarkGisi** [comment]
Not sure how that might be included in the spec. We do make the point in the spec FAQ (which is referenced in the spec Introduction)  that no legal advise is provided in the spec:

https://wiki.linuxfoundation.org/openchain/specification-questions-and-answers#what_are_the_specification_guiding_principles

https://wiki.linuxfoundation.org/openchain/specification-questions-and-answers?&#does_the_specification_describe_how_to_comply_with_the_most_popular_open_source_licenses
