### ISSUE TITLE
Is section 5 of spec version 1.2  an asset or inhibitor (Japan Work Group May 2018)

### ISSUE THREAD

**Issue by MarkGisi** [OpenChain-Project/License-Compliance-Specification#14]
Initial comment:
Items of Goal 5 of the specification are related to contributions to FOSS projects. These items seem to be not directly related to supply chain compliance. Why are these items included in the spec?

**Comment by MarkGisi** [comment]
This is feedback that was been raised before – most recently by Till Jaeger during the version 1.2 Public Comments period. We can revisit the discussion - if  section 5 could be moved to an optional section?

**Comment by jlovejoy** [comment]
I still think this is important to include and I think the way we have it does not make it an onerous requirement. OpenChain described "effective FOSS management" which is the whole picture, not just license compliance alone.

**Comment by MarkGisi** [comment]
>> OpenChain described "effective FOSS management" which is the whole picture, not just license compliance alone.

We need to make an important distinction between Openchain i) as a project and its mission and ii) the objectives of the OpenChain (compliance) spec initiative - which is just one deliverable of the project. I agree the project is focused on a broader mission of facilitating the managing open source. The spec initiative, which delivers on an important component of the larger mission, is focused on one core piece:
              Enable an organization to establish trust with others (both internal and external) that the open source license compliance artifacts they deliver with their software solutions are of high quality.

Without quality compliance artifacts , legally, an organization has not effectively secured the required rights to distribute any products that use open source. This is ground zero for open source use and adoption. The contribution activity – although extremely important, is different. Everyone is required to comply with the licenses governing the use open source they use, but not everyone is required to contribute.  The more focused the spec is, the more likely it will be successful. We want to avoid the spec from becoming:   “a jack of all trades (and master of none)”

It is my belief - that Section 5 (the contributions portion) of the spec adds friction to the spec’s adoption while under serving an organization’s contribution programs. What I am hearing from companies that are less mature on the compliance front (or from large companies working with smaller ones) is that - the spec’s extra demand for contribution management (Section 5) is somewhat burdensome and concerning. I do not necessarily believe it is overly burdensome give how thinly  drafted it is. So thinly drafted that I believe it does not to have “enough wood behind the arrow” to be effective.

Section 5 detracts from the license compliance part while  underserving the contribution component of the project’s larger mission. We have to collectively agree that although compliance and contributions activities are both important and related, they are different. To borrow from the English phrase “comparing apples and oranges”, Sections 1-4 of the spec are apples and section 5 the oranges (although few). Having noted that, there are other deliverables the OpenChain project can provide  to better support a company’s contribution program. Perhaps a dedicated ‘contribution’ spec or a collection of best practice docs would better serve the contribution component of the OpenChain project’s larger mission. I suggested back in the first draft of the spec that we could include an “optional” contributions section which would enable earning an additional (but not required) conformance badge.

All in  all, by separating compliance and contributions, we would allow the compliance spec to become  “the master of one” - ensuring  higher quality license compliance, and thereby, securing a supply chain’s ability (i.e., rights) to more easily exchange software solutions built on open source software.

- Mark

**Comment by MarkGisi** [comment]
Hi Mark, all

I think it is a really important point that the specification is focused on one clear goal:
“Enable an organization to establish trust with others (both internal and external) that the open source license compliance artifacts they deliver with their software solutions are of high quality.”

I do not think this precludes organizations from having a process of pro-active engagement and contribution to the community - and I believe the OpenChain Project can usefully provide plenty of reference material in this regard - but I do think we would benefit from being careful to ensure that it is equally valid to have no contribution as it is to have some or substantial contribution.

For this reason I tend to agree with Mark that our feedback from deployment indicates that a stronger separation of compliance and contribution would be beneficial for the specification (again, not precluding OpenChain Project having substantial resources to explain and guide great contribution).

Regards

Shane

**Comment by MarkGisi** [comment]
Hi Shane-san and Mark-san,

IMHO.
About the separation of compliance and contribution,
I am afraid that a wrong message (“you do not have to think of contribution”)
may be received by a company which should contribute to a community.
(I know you do not intend to preclude contribution.)

To avoid such misunderstandings, we should be careful.
We may need to explain very carefully the big picture and the reason of separation
and  the importance of contribution, in the specification.


---
Hiro Fukuchi (Hiroyuki.Fukuchi@sony.com)
Sony

**Comment by MarkGisi** [comment]
Hi Fukuchi San!

I think we may need to separate “license compliance" and “effective use" of open source. Of course license compliance is part of effective use of open source, but there are many other parts of effective use, including contribution. Two points stick out:
(a) License compliance can happen with no contribution. 
(b) This does not mean maximum open source value. 
I believe both are important points.

As a project, OpenChain has a mission to build trust in open source by making open source license compliance simpler and more consistent. There are two major parts to this:
(1) The OpenChain Specification defines a core set of requirements every quality compliance program must satisfy. 
(2) The OpenChain Curriculum provides the educational foundation for open source processes and solutions, whilst meeting a key requirement of the OpenChain Specification.

Basically (1) - the Specification - is purely about requirements that compliance programs must satisfy.
(2) is where we provide knowledge about great open source processes and solutions. This covers the specification requirements but it also covers other things, like “effective use” and how to get maximum value.

I understand Mark is concerned that because (1) is purely about requirements for compliance programs, having contribution items may provide confusion and a barrier to entry; for example a company wanting to have compliance but not contribution may become worried about Section 5. His suggestion is to clearly separate compliance and contributions to allow the compliance spec to become “the master of one” - or meet its design goal as cleanly as possible.

My personal feeling is that it may be beneficial to have each part of the project as simple as possible. For example, keeping the Specification “single mission” so that it can quickly be understood and adoption seems straightforward for many different types of entity. At the same time, I see a *lot* of companies coming to OpenChain looking for strategic help and reference material. This is where the Curriculum seems very important to me. Showing people how to get value from open source - by contributing, by communicating, by collaborating - is right beside license compliance is ensuring effective use.

Regards

Shane

**Comment by MarkGisi** [comment]
Based on recent working group discussions there are mixed views on whether to maintain section 5 or possibly make it optional. Due to a lack of general consensus the decision is to leave section 5 as is (i.e., neither remove or extend).
