### ISSUE TITLE
Fix spelling mistake `inquires`

### ISSUE THREAD

**Issue by tsteenbe** [OpenChain-Project/License-Compliance-Specification#18]
In 2) Definitions: Open Source FOSS Liaison-a designated person who is assigned to receive external Open Source FOSS inquires ... last bit should be `inquiries`

**Comment by MarkGisi** [comment]
fix has been made in the most recent spec 2.0 draft.

**Comment by HansMKern** [comment]
@MarkGisi, can you provide the current (fixed) version as markdown in this repository? It would enable a better collaboration, because we could discuss on the document (in line) and we could also propose changes as a pull request, which again can be discussed.

see #19 

Thanks
