### ISSUE TITLE
Provide the current draft as markdown in this repository

### ISSUE THREAD

**Issue by HansMKern** [OpenChain-Project/License-Compliance-Specification#19]
can you provide the current (fixed) version as markdown in this repository? It would enable a better collaboration, because 

- we could discuss on the document (inline), 

- we could also propose changes as a pull request, which again can be discussed inline 

- and it also provides a better traceability of the changes and contributions to the document

**Comment by theopenchainproject** [comment]
I concur.

Spec 1.2 is available in MarkDown here:
https://github.com/OpenChain-Project/Specification/blob/master/OpenChainSpec-1.2.TranslationTemplate.md.txt

I believe it would be really useful if we could also place Spec 2.0 draft in this repo as Doc+Markdown. My suggestion is that we do this alongside merging the separate https://github.com/OpenChain-Project/spec-2.0 repo.

**Comment by MarkGisi** [comment]
We are in the last stage of the spec release cycle. I would like to keep the process the same through the release of the version 2.0 of the spec. We can revisit the process at the start of the next cycle to look for ways to improve it.  We can consider markdown at that time.

**Comment by theopenchainproject** [comment]
Thanks Mark! Makes sense.

**Comment by HansMKern** [comment]
Great work @MarkGisi! Thanks alot.

**Comment by MarkGisi** [comment]
This was discussed at the OpenChain F2F meeting at the Open Source Summit - 2019 (San Diego). 

It was generally recognized that a the availability of a markdown version would be beneficial. The new challenge presented with version 2.1 is that it has been submitted for ISO adoption and that ISO requires the spec be maintained using a specific formatting. Currently markdown is not feature rich enough to support the ISO formatting standards.
