### ISSUE TITLE
Minor edit: suggest CC-BY-4.0 (with hyphens) for license ID

### ISSUE THREAD

**Issue by swinslow** [OpenChain-Project/License-Compliance-Specification#22]
I recognize that this is a super-nitpicky comment. Apologies in advance for being pedantic  =)

On pages 2 and 13, where the spec license is listed, it is stated as "CC-BY 4.0". I'd suggest adding the second hyphen, to make it "CC-BY-4.0", for alignment with IDs on the SPDX license list.

**Comment by swinslow** [comment]
A perhaps-related nit, on page 5 (Definitions) where "SPDX" is defined, the full project name listed there is incomplete. It should be the Software Package **Data** Exchange.

**Comment by MarkGisi** [comment]
Excellent - no correction is too small. Fixed.
