### ISSUE TITLE
inbound license policy vs outbound license policy

### ISSUE THREAD

**Issue by MarkGisi** [OpenChain-Project/License-Compliance-Specification#28]
1.1: “governs Open Source license compliance of the Supplied 
Software” can be understood as just inbound license policy, or to also 
include the outbound license policy. I’m totally fine with that, but 
we do have this in separate documents.

**Comment by silverhook** [comment]
To expand on this, as I was the one originally asking, the “Open Source policy” at least in Spec 2.0 is not defined in detail.

I assume the text in _1.1 Policy_ at least started with the inbound licensing policy in mind, but it can just as easily be read to include FOSS licensing questions on the outbound side as well (i.e. organisation releases code as FOSS).

In general, this seems perfectly fine to me.

What bothers me a bit is that this gives me some confusion between _1.1 Policy_ and _5.1 Contributions_, as the former talks about the general (also) outbound policy, while the latter about a policy specifically about _contributions to_ FOSS projects, which seems to assume that the organisation/Program contributes to _existing_ FOSS projects, and ignores the option of the organisation/Program to release and maintain their own FOSS projects.

The way I see it, it seems reasonable for OpenChain Spec to include the use case of the organisation/Program releasing their own FOSS projects, but I find it tricky to decide under which section of the Spec 2.0 this falls under – verification material 1.1.1 or 5.1.2-3?

**Comment by MarkGisi** [comment]
This was discussed at the F2F meeting at the Open Source Summit - 2019 (San Diego). 

It was generally understood that an organization has a choice of which section it falls under. It was also generally agreed upon that it is likely that more organizations will choose to document there own Open Source projects under section 5 - since they represent open source contributions which they happen to be the lion share contributor. That is, contributing to the Linux Kernel and hosting an open source project on one's publicly available website would each represent a contribution to a project. 

It was also pointed out that would be a common practice for that an organization to maintain a single Open Source policy document that covered 1.1.1 and 5.1.1.

**Comment by silverhook** [comment]
As long as this understanding is logged somewhere (or even referred to), it sounds OK to me to keep the spec as is in this regard.
