### ISSUE TITLE
enforcing 18 month conformance requirement

### ISSUE THREAD

**Issue by MarkGisi** [OpenChain-Project/License-Compliance-Specification#32]
6.2: How would the conformance be enforced in practice every 18 
 months?

**Comment by silverhook** [comment]
To come back to this (I was the person asking initially), from what I was made to understand, the idea is that just as the 6.1(.1), also the 6.2(.2) fall under self-assessment – i.e. the (self-)assessor of the Program in both cases writes the document and keeps it in their archives.

6.1.1 for initial conformance and then as 6.2.1 do a self-re-assessment every 18 months, to see if the Program still complies and/or if there needs to be anything updated in the (self-)assessment document.

If that is the case, it makes sense to me, but would perhaps need to be clarified better at least in explanatory material outside of the Spec.

**Comment by MarkGisi** [comment]
This was discussed at the F2F meeting at the Open Source Summit - 2019 (San Diego). 

As with each requirement - there is flexibility to how one can implement a requirement. It is the project's intent for others to publish the different ways they satisfy each requirement. I hope others will over time. One way to achieve this requirement could be the existence of a documented attestation declaring conformance was achieved and the date submitted to the project's Conformance  website. If audited (e.g., by a supplier's customer) one could present the document.
