### ISSUE TITLE
Normative References - for consideration in ISO draft

### ISSUE THREAD

**Issue by andrewjskatz** [OpenChain-Project/License-Compliance-Specification#34]
The draft is dependent on the OSD and FSD (see section 3.4). Consideration should therefore be given to referencing these in the section 2 (Normative References). 

There is also some text after 3.9 which refers to external documents, but it is not clear that that text is necessary (ISO and IEC maintain terminological databases.....http://www.electropedia.org/) so I would propose deleting it.

**Comment by zvr** [comment]
If I remember correctly, OSD and FSD _were_ normative references in the early drafts, but the editor (experienced in ISO writings) moved them to the Bibliography section. He provided a rationale for this in an email or a comment in the Word file.

**Comment by andrewjskatz** [comment]
Thanks Alexios. I will try to track down the rationale. This is quite surprising, as there are several places where 'open source' constitutes a requirement (for example, in 4.3.1 it is necessary that the bill of materials contains each open source component contained in the supplied software). Therefore, to comply with this, it is necessary to know what 'open source' means with a degree of precision, and therefore the references to OSD and FSD are necessary (because of 'or similar license' in the definition of open source, it is of course possible for an implementer to choose a _wider_ definition, thus including additional material within the BOM - this is fine. But to determine the minimum scope of what open source means, it's necessary to refer to the OSD and FSD, which in my view makes the references normative. https://isotc.iso.org/livelink/livelink/fetch/2000/2122/4230767/Drafting_standards_-_Frequently_asked_questions_%28FAQ%29.pdf?nodeid=18973477&vernum=-2

I'm very happy to be convinced otherwise, though.

**Comment by MarkGisi** [comment]
The Open Source definition, as you could imagine, has been much debated. We can continue this discuss in the next major revision of the spec.

**Comment by andrewjskatz** [comment]
Thanks Mark. Maybe I wasn't clear enough, but this isn't a debate about the OSD (which is irrelevant as the 'or similar licences' has, correctly, in my view, defused that debate.) What is more significant, is around what a normative reference is (and this is critical for the ISO submission, so unlike many of my other comments can't be held over to the next iteration). 

The point is that for an implementer to know they are compliant, they must implement their program in such a way that it covers (at a minimum) open source software. They can, of course, define a wider program which also covers software which is wider than that definition. For that reason, they must refer to the then-current definition of OSD and FSD, which means that the references are normative. As a thought experiment, imagine that those references are undefined and there is no such thing as OSD or FSD. In that case, the specification becomes meaningless. Therefore, the definitions of OSD and FSD become critical to interpretation, and need to be referenced normatively.

**Comment by zvr** [comment]
Wasn't this discussed and closed in the face-to-face meeting in Lyon?

**Comment by MarkGisi** [comment]
Yes. Andrew made a valid point, but after a extended discussion by the Technical Advisory committee it was decided to remove the Normative References section. This was done in draft version rc1.
