### ISSUE TITLE
Consider adding definition of 'bill of materials' - for consideration in next iteration

### ISSUE THREAD

**Issue by andrewjskatz** [OpenChain-Project/License-Compliance-Specification#35]
'bill of materials' is a well-understood term to those involved in software composition analysis and compliance, but it does stretch the natural meaning somewhat. For clarity, we should consider adding an explicit definition in the Terms and Definitions section.

**Comment by MarkGisi** [comment]
Ok. We can include it in the next major spec revision.

**Comment by andrewjskatz** [comment]
Pinging for consideration in next major revision.

**Comment by zesoup** [comment]
After the recent discussion which touched on the point of depth or granularity of the bill-of-material i'd like to add the point of 'relevance' to the program from a legal perspective.

As the major point of openchain at the moment is focused around legal compliance i wonder if we could define that all components with 'significant relevance to the supplied product' need to be listed.  In that regard i'd like to assume that a GPL-Software that is a one-liner or just shipped by accident in my container will not cause major commercial damages, while the violation of a major framework would most likely do.

As it is of course highly speculative where that border of significance lies it should be the border a conformant needs to actively define and as such, a documented definition of a bill of material is a nice addition.

Thoughts?

**Comment by stephenkilbaneadi** [comment]
Proposal:

2.10 Bill of Materials
A machine-readable list of distinct components included in the Supplied Software, expressed in a standard format such as SPDX. Typically, the "distinct components" are open source software packages or other third-party content that have been incorporated into the Supplied Software.

**Comment by stephenkilbaneadi** [comment]
Also, we should then apply the defined term consistently. We currently have "bill of materials" and "open source bill of materials".

Do we want "Bill of Materials" or "Software Bill of Materials (SBOM)", to reflect the growing use of the "SBOM" term?

**Comment by heliocastro** [comment]
There's a thin line or how we call the definitions. Bill of Materials can reflect way more than software, it can for example be a document to represent any hardware machine composition without any software related.
OpenChain is rooted for Software Bill of Materials and we can't simply reduce the term for BIll of Materials and in the same sentence, as 2.10, mention Software in key components.

**Comment by heliocastro** [comment]
@stephenkilbaneadi One thing that we should be more careful is explicit standards mention.
While i agree with your 2.10 entry with the addition if  _Software_ as main suffix, the sentence should be reduced to **expressed in a standard format.**, preventing to mention an specific standard.

**Comment by stephenkilbaneadi** [comment]
I added SPDX as an example because we _already_ have SPDX defined as a term in the standard, as a format for BOMs.

**Comment by heliocastro** [comment]
Proposal was revisiting the terminology.
One solution is rely on [NTIA definition](https://ntia.gov/page/software-bill-materials) and remix slightly the language to adapt to current OpenChain spec definition style.

**Comment by shanecoughlan** [comment]
From NTIA:

A “Software Bill of Materials” (SBOM) is a nested inventory for software, a list of ingredients that make up software components.

**Comment by shanecoughlan** [comment]
Proposal as per team call of 2023-06-06:

a “Software Bill of Materials” (SBOM) can be understood as a [complete][comprehensive][nested] inventory for software, a list of ingredients that make up software components. An example is the specification created by the Linux Foundation's SPDX (Software Package Data Exchange) Working Group for exchanging bill of materials for a given software package, including associated license and copyright information (see [spdx.org](https://spdx.org/)).

This would replace 2.7 in the existing Specification 3.0 Draft document.

RFC by 19th June COB US Pacific.

**Comment by shanecoughlan** [comment]
Potential spin:

a “Software Bill of Materials” (SBOM) can be understood as a complete inventory for software, a list of ingredients that make up software components. An example is the specification created by the Linux Foundation's SPDX (Software Package Data Exchange) Working Group for exchanging bill of materials for a given software package, including associated license and copyright information (see [spdx.org](https://spdx.org/)).

**Comment by shanecoughlan** [comment]
Or

a “Software Bill of Materials” (SBOM) is a complete inventory for software, a list of ingredients that make up software components. An example is the specification created by the Linux Foundation's SPDX (Software Package Data Exchange) Working Group for exchanging bill of materials for a given software package, including associated license and copyright information (see [spdx.org](https://spdx.org/)).

**Comment by shanecoughlan** [comment]
Merged.
