### ISSUE TITLE
A few typos

### ISSUE THREAD

**Issue by andrewjskatz** [OpenChain-Project/License-Compliance-Specification#37]
3.2 identified licenses: there is a stray capital S in 'software'

**program participants**: there seems to be some inconsistent usage of participants, program participants and program personnel: 

See 4.1.2 rationale (should read _To ensure that the identified **program** participants ~~fulfilling program roles~~ have obtained a sufficient level of competence for their respective roles and responsibilities_

4.1.3 Verification Materials - program personnel should be program participant
4.1.3 Rationale: program personnel should be program participant

Other typos: 
4.1.3 - stray capital P in Program's (see bullet 4)

**Comment by MarkGisi** [comment]
Thanks for the recommended wording change. It was updated to:

Ensure that the program participants have obtained a sufficient level of competence for their respective roles and responsibilities.
