### ISSUE TITLE
Verification Material For Training - next iteration

### ISSUE THREAD

**Issue by andrewjskatz** [OpenChain-Project/License-Compliance-Specification#38]
This point came up when I submitted the template open source policy for review. There seems to be no requirement for documentation evidencing that a training program exists (although, as I pointed out in comments to the suggestion on the template policy, this can be inferred from the results of the assessment of competence).

I would suggest something like a new bullet or two between the number 1.2.2 and 1.2.3 in section 4.1.2 (the numbering is awry - see my other issue) which says something like
- Documented evidence that an appropriate training course or courses exist and have been undertaken by program participants

**Comment by MarkGisi** [comment]
In the current spec it states:
    Documented evidence of assessed competence for each program participant.

This should address the issue you raised. Note that within an organization not everyone is expected to take a training course. For example, Legal professionals might have satisfy the competence requirement by passing a bar exam and/or have a legal degree. Some organizations my require an online test to be passed. It is left to the organization to decide how to assess competence.

**Comment by andrewjskatz** [comment]
Sorry to reopen this, but it has been a live issue on conformance exercises, and as it stands it makes it difficult to come up with an audit specification if there is only verification material for assessments. I would rather see a requirement to see a training and assessment policy (even if it's lightweight) than nothing at all. It seems a little inconsistent with the remainder of the OpenChain ethos so only assess training and assessment outcomes, as opposed to  the procedures that led there (like just running a code scan on a particular software release, rather then having a set of policies and procedures to show how a conformant set of code was achieved).

**Comment by Dr-wood** [comment]
@andrewjskatz @MarkGisi Do you believe that the requirement for training awareness etc is now adequately addressed in the current version of the ISO spec or in the draft that we are working on to allow us to close this issue? @shanecoughlan

**Comment by shanecoughlan** [comment]
Suggest we return to this for the next North America / Europe call, picking up the thread with the same participants online.

**Comment by Dr-wood** [comment]
ShaneSounds goodChrisOn Mar 18, 2024, at 5:41 PM, Shane Coughlan ***@***.***> wrote:﻿
Suggest we return to this for the next North America / Europe call, picking up the thread with the same participants online.

**Comment by shanecoughlan** [comment]
> Sorry to reopen this, but it has been a live issue on conformance exercises, and as it stands it makes it difficult to come up with an audit specification if there is only verification material for assessments. I would rather see a requirement to see a training and assessment policy (even if it's lightweight) than nothing at all. It seems a little inconsistent with the remainder of the OpenChain ethos so only assess training and assessment outcomes, as opposed to the procedures that led there (like just running a code scan on a particular software release, rather then having a set of policies and procedures to show how a conformant set of code was achieved).

@andrewjskatz we are unable to proceed on this issue without additional discussion. Would it be possible to propose new example language for a relevant section of the Specification? While we do not plan to copy/paste such an example, it would be useful to fully understand the proposed addition and its placement.

**Comment by andrewjskatz** [comment]
@shanecoughlan - yes indeed. Sorry I can't be on the call right now. I've given this some additional thought. There seems to be a gap in the specification as it stands, in that it does not talk about a training and assessment policy/procedure, but goes straight from identifying competencies, to assessing competencies without the intermediate step of providing training or education where appropriate. This makes auditing difficult (and it's an issue which came up in a live engagement). I would propose a new verification material, between 3.1.2.2 and 3.1.2.3 as follows:

_3.1.2.3 A documented procedure to assess the competencies of program participants and provide training and education or review of the relevant role as appropriate_

I hope this is helpful.

**Comment by Dr-wood** [comment]
Andrew and Shane. It might be good to add a “for example” referencing the Secure Software Development Framework SP 800-218 which specifically mentions documenting training and several other key subjects in PO.2 task PO 2.2 as part of the management and governance processes of secure software development. On Apr 2, 2024, at 12:07 PM, Andrew Katz ***@***.***> wrote:﻿
@shanecoughlan - yes indeed. Sorry I can't be on the call right now. I've given this some additional thought. There seems to be a gap in the specification as it stands, in that it does not talk about a training and assessment policy/procedure, but goes straight from identifying competencies, to assessing competencies without the intermediate step of providing training or education where appropriate. This makes auditing difficult (and it's an issue which came up in a live engagement). I would propose a new verification material, between 3.1.2.2 and 3.1.2.3 as follows:
3.1.2.3 A documented procedure to assess the competencies of program participants and provide training, education or review of the relevant role as appropriate
I hope this is helpful.

**Comment by shanecoughlan** [comment]
### RECAP

**Suggested change is to add:**

3.1.2.X A documented procedure to assess the competencies of program participants and provide training and education or review of the relevant role as appropriate

**The current material is:**

3.1.2 - Policy

A written open source policy shall exist that governs open source license compliance of the supplied software. The policy shall be internally communicated.

Verification material(s):

3.1.2.1 - A documented open source policy.
3.1.2.2 - A documented procedure that makes program participants aware of the existence of the open source policy (e.g., via training, internal wiki, or other practical communication method).

Rationale:

To ensure steps are taken to create, record and make program participants aware of the existence of an open source policy. Although no requirements are provided here on what should be included in the policy, other sections may impose requirements on the policy.

3.1.3 - Awareness

The organization shall ensure that the program participants are aware of:

The open source policy;
Relevant open source objectives;
Their contribution to the effectiveness of the program; and
The implications of not following the Program's requirements.

Verification material(s):

3.1.3.1 - Documented evidence of assessed awareness for the program participants - which should include the program's objectives, one's contribution within the program, and implications of program non-conformance.
Rationale:

To ensure the program participants have obtained a sufficient level of awareness for their respective roles and responsibilities within the program.

**Comment by shanecoughlan** [comment]
### Concern

3.1.2 is scoped to policy as opposed to general training and education.

### Proviso

3.1.3 **is** a leap, in that is talks about what people must be aware of including and beyond the policy.

### Situation

We are missing the middle step of how to get from policy to awareness if awareness goes beyond the policy itself.

**Comment by shanecoughlan** [comment]
### Suggested Resolution

I have a suggestion to keep 3.1.2 focused on policy but make 3.1.3 include education or training as part of awareness.

### Specific Change

The specific change is the *addition* of:

3.1.3.1 - Documented evidence of training or education material for program participants which should include the open source policy, Program objectives, contribution within the Program, and implications of Program non-conformance.

The *adjustment* of:

3.1.3.1 - Documented evidence of assessed awareness for the program participants - which should include the program's objectives, one's contribution within the program, and implications of program non-conformance.
to 
3.1.3.2 - Documented evidence of assessed awareness for the program participants which should include the open source policy, Program objectives, contribution within the Program, and implications of Program non-conformance.
[RATIONALE: original did not include open source policy yet that was referenced in the bullet points]

and

3.1.2.2 - A documented procedure that makes program participants aware of the existence of the open source policy (e.g., via training, internal wiki, or other practical communication method).
to
3.1.2.2 - A documented procedure that makes program participants aware of the existence of the open source policy (e.g., via training or other practical communication method).
[RATIONALE: "internal wiki" is technology dependent and potentially redundant given "or other practical communication method" exists]

### This would make the full text

3.1.2 - Policy

A written open source policy shall exist that governs open source license compliance of the supplied software. The policy shall be internally communicated.

Verification material(s):

3.1.2.1 - A documented open source policy.
3.1.2.2 - A documented procedure that makes program participants aware of the existence of the open source policy (e.g., via training or other practical communication method).

Rationale:

To ensure steps are taken to create, record and make program participants aware of the existence of an open source policy. Although no requirements are provided here on what should be included in the policy, other sections may impose requirements on the policy.

3.1.3 - Awareness

The organization shall ensure that the program participants are aware of:

- The open source policy;
- Relevant open source objectives;
- Their contribution to the effectiveness of the program; and
- The implications of not following the Program's requirements.

Verification material(s):

3.1.3.1 - Documented evidence of training or education material for program participants which should include the open source policy, Program objectives, contribution within the Program, and implications of Program non-conformance.
3.1.3.2 - Documented evidence of assessed awareness for the program participants which should include the open source policy, Program objectives, contribution within the Program, and implications of Program non-conformance.

Rationale:

To ensure the program participants have obtained a sufficient level of awareness for their respective roles and responsibilities within the program.

**Comment by shanecoughlan** [comment]
On call of 2024-05-07 we concluded:

Comments ahead of North America / Asia call in two weeks please.

**Comment by shanecoughlan** [comment]
Closed and to be merged with 3.0 draft, no objections raised in the comment period outlined above. No objection raised during the recap on our call on 2024-05-21.
