### ISSUE TITLE
3.8 supplied software - for discussion in subsequent iteration

### ISSUE THREAD

**Issue by andrewjskatz** [OpenChain-Project/License-Compliance-Specification#40]
Should the _distributes_ extend to _distributes or makes available_? This allows organisations to designate a SaaS product as being subject to an OpenChain program (of course, there is no requirement to make all products subject to an OpenChain program, but this may affect those organisation which have self-declared as being 2.0 compliant without that compliance extending to their SaaS offerings.

**Comment by MarkGisi** [comment]
It is not clear what all the implications of this addition would be. In the 2.1 draft an organization needs to specify the program scope - e.g., they could designate an entire division or the entire company. Now all SaaS solutions of that division (or company)  must be OpenChain  conforming. Under the "current" wording all software distributed by the SaaS would still be covered (e.g., downloadable clients or browser javascript code) - but not the backend. It may turn off some SaaS providers if they needed to include the back end.

Another question: To what degree do most SaaS end users care about OpenChain conformance? Would this addition add a meaningful level of trust that is missing today? Let's move this discussion to the next major draft version and seek input from SaaS providers (and their users).

**Comment by andrewjskatz** [comment]
Thanks Mark. Now pinging as we are considering the next iteration. This is a live issue for me, as I have clients who want to embrace conformance for SaaS-delivered services (some of which use AGPL). Maybe the solution is for the default assumption for organisations who have chosen the company, business units or divisions to be within scope that SaaS offerings are *not* included, unless they are explicitly opted in.

**Comment by zesoup** [comment]
I would like to expand upon the case of SaaS not being distributed but within scope. In that regard it'd be possible to have a SaaS-backend OpenChain Compliant without ever looking at the BoM, as we deem it not being distributed. 

The Programs Scope should make it perfectly clear which software and divisions are to be openchain compliant, so is it wise to make a statement about what software should and should not be covered by default?

Especially looking at the chance of OpenChain 3.0 being heavier on a BoM-Foundation with optional substandards the use of openchain is wider than the legal implications which dictate the current "distributes". E.G. for a Security-Module the physical distribution might not be the best selector for openchains relevance to software.

**Comment by james-sorling-wcar** [comment]
"SaaS-backend OpenChain Compliant", could contain Affero GPL components or any other license where network transmission is enough so BoM analysis still required.

**Comment by HansMKern** [comment]
What is considered as "distribution" varies from license to license and may also have different triggers in the applicable copyright law.

And, as far as INAL, if you are not the operator of the SaaS hosting, you distribute to the legal entity that does the operation for you. And if the distribution to the hosting is triggering the "distribution fulfillment" in the OSS license depends.

So, I would stick to a more broader approach where you (and your legal advisor) should come up with an interpretation yourself where and how much you'll BoM in SaaS.

**Comment by Dr-wood** [comment]
@shanecoughlan We discussed this and are unsure how to move forward without a deeper technical/legal discussion on the specifics of the new licensing schemes related to this and how to incorporate the changes to the 3.0 md language ""software that an organization distributes to third parties (e.g., other legal entities, other organizations or individuals)""

**Comment by winterrocks** [comment]
> Should the _distributes_ extend to _distributes or makes available_? This allows organisations to designate a SaaS product as being subject to an OpenChain program (of course, there is no requirement to make all products subject to an OpenChain program, but this may affect those organisation which have self-declared as being 2.0 compliant without that compliance extending to their SaaS offerings.

In general, I think that it would reduce (or even remove) some misunderstandings that **making SW available for download,** counts as distribution, even if nobody really downloads the SW. At least this is something that most of the Legal folks have been saying.

**Comment by Dr-wood** [comment]
Thank you Jari as always I do appreciate hearing from you. Your point of view is valuable. Best RegardsChrisOn Mar 5, 2024, at 1:02 PM, Jari Koivisto ***@***.***> wrote:﻿

Should the distributes extend to distributes or makes available? This allows organisations to designate a SaaS product as being subject to an OpenChain program (of course, there is no requirement to make all products subject to an OpenChain program, but this may affect those organisation which have self-declared as being 2.0 compliant without that compliance extending to their SaaS offerings.

In general, I think that it would reduce (or even remove) some misunderstandings that making SW available for download, counts as distribution, even if nobody really downloads the SW. At least this is something that most of the Legal folks have been saying.

**Comment by shanecoughlan** [comment]
Suggest we return to this for the next North America / Europe call, picking up the thread with the same participants online.

**Comment by Dr-wood** [comment]
ShaneSounds good. Perhaps we cat get these closed out or moving in that direction. ChrisOn Mar 18, 2024, at 5:41 PM, Shane Coughlan ***@***.***> wrote:﻿
Suggest we return to this for the next North America / Europe call, picking up the thread with the same participants online.

**Comment by shanecoughlan** [comment]
The question of whether replacing the term _distributes_ with _distributes or makes available_ provides additional value is undetermined in our conversations as per call 2024-04-02. 

The key question is whether the interpretation of distribution includes or can include make available, or another term is needed. 

As per the call 2024-04-02, the specification is regarded as accurate, and therefore this issue will be closed. It may be reopened if it is determined to be important by enough parties.
