### ISSUE TITLE
3.9 verification materials - for discussion in subsequent iteration

### ISSUE THREAD

**Issue by andrewjskatz** [OpenChain-Project/License-Compliance-Specification#41]
For clarity the following wording should be added:

materials that demonstrate that a given requirement _of the program_ is satisfied

This removes that ambiguity that the requirement is a requirement of the OpenChain program, not a requirement of a license for example.

**Comment by MarkGisi** [comment]
Actually the "requirement" here is that of the specification. Therefore I would recommend:

      materials that demonstrate that a given requirement _of the specification_ is satisfied

**Comment by andrewjskatz** [comment]
Yes - great - can we say materials that demonstrate that a given requirement _of the specification_ is satisfied for the _Program_. This is more consistent with the rest of the wording in the specification (which talks about requirements of a Program meeting the Specification - see 6.2 for example). Also (sorry) I have noticed inconsistency in the capitalisation of "Specification".

**Comment by MarkGisi** [comment]
I fixed the wording in the 6.2 rationale to refer to the program (not organization) when referring to the specification.
