### ISSUE TITLE
2.7 broaden intent of SPDX

### ISSUE THREAD

**Issue by iamwillbar** [OpenChain-Project/License-Compliance-Specification#42]
In 2.7 SPDX is cast as being specifically for sharing license and copyright information, however, we are actively ensuring that SPDX is suitable for broader software bill of material uses. See this PR which is being incorporated in the SPDX 2.2 specification: https://github.com/spdx/spdx-spec/pull/150.

To align with this I would suggest changing:
`for exchanging license and copyright information for a given software package`

To:
`for exchanging bill of materials for a given software package, including associated license and copyright information`

**Comment by kestewart** [comment]
Agree.   We've adopted this new text in SPDX 2.2, and it would be good that the definition in open chain reflected the agreed on update.

**Comment by HansMKern** [comment]
Makes sense.

**Comment by MarkGisi** [comment]
The SPDX definition was updated to include reference to bill of materials. It now reads:

"the format standard created by the Linux Foundation’s SPDX (Software Package Data Exchange) Working Group for exchanging bill of materials for a given software package, including associated license and copyright information (see spdx.org)"
