### ISSUE TITLE
v2.1 § 3.4.1.1 - provide example of commonly-missed compliance artifact

### ISSUE THREAD

**Issue by ossguy** [OpenChain-Project/License-Compliance-Specification#43]
As requested on the OpenChain Project Specification Work Group mailing list, I am submitting the following public comment.  I was unable to add this as a pull request, since I couldn't find the source code for v2.1 (only v2.0 and earlier are at https://github.com/OpenChain-Project/Specification/tree/master/version with no branches aside from master).  If I am looking for the v2.1 source code in the wrong place (i.e. for the https://wiki.linuxfoundation.org/_media/openchain/openchainspec-2.1.draft.pdf document), please let me know.  Anyway, here is the suggestion:

Add to the end of Section 3.4.1.1 (after "by the identified licenses."):

"For example, with most popular copyleft licenses the compliance artifacts must include instructions for installing modified versions of the supplied software on the target device."

The above describes a portion of the required compliance artifacts that are commonly missed (in my experience) when the supplied software contains code under copyleft licenses.  It would be good to include this example so that users of the OpenChain specification do not unintentionally omit such compliance artifacts and are thus not able to list themselves as OpenChain conformant.

Denver Gingerich
Software Freedom Conservancy

**Comment by MarkGisi** [comment]
Thanks Denver for the thoughtful feedback. 

>>  I was unable to add this as a pull request,

Due to logistical reasons - i.e., the spec is maintain in MS word  due to special OSI formatting requirements, and therefore - we cannot handle pull requests. However we use github to maintain this issues for historical record purposes. 

>> "For example, with most popular copyleft licenses the compliance artifacts must include 
>> instructions for installing modified versions of the supplied software on the target device."

One core goal of the spec, as noted in the Introduction and wiki FAQ,  is it focuses on the "what and why" aspects of a trusted compliance program and not the "how and when". The spec's main point in 3.4.1.1 is to ensure every compliance program maintains a "process for creating the set of compliance artifacts for the supplied software." 

Having noted that, the OpenChain project assumes (encourages) others to produce best practice documents recommending how to successful implement such a process ("how and when"). Your comment, which represents a good piece of process implementation advice; although out of scope for the spec, would be helpful to a program implementer. 

Another note worth mentioning is that the spec also avoids including legal advice (e.g., license interpenetration).

**Comment by bkuhn** [comment]
@MarkGisi said OpenChain's primary goal is to help with:
> "process for creating the set of compliance artifacts for the supplied software."

It seems important that OpenChain should mention in the spec that compliance artifacts for copyleft licenses often require "instructions for installing modified versions of the supplied software on the target device".

Why  is the OpenChain project choosing to avoid mentioning this important issue?  Any compliance process that doesn't say *what* copyleft-based compliance artifacts must include is surely inadequate, no?

You may be right, @MarkGisi, that Section 3.4.1.1 might be the wrong place to mention this matter.  Another option would be to mention it in 2.2.1, updating that definition to read as follows:

>> Note: The collection may include (but is not limited to) one or more of the following: source code, instructions for installing modified versions of the supplied software on the target device,  attribution notices, copyright notices, copy of licenses, modification notifications, written offers, open source component bill of materials, and SPDX documents.

Notwithstanding that the phrase "but is not limited to" is already contained, for copyleft licenses, installation information is a much more important issue than most of the other things that are explicitly listed.

Could @ossguy's suggestion thus instead be added to section 2.2.1 instead as suggested herein?  If not, why not?

@MarkGisi noted further:
> Another note worth mentioning is that the spec also avoids including legal advice (e.g., license interpenetration [sic]).

Nothing proposed by @ossguy appears to be legal advice nor license interpretation, so this point above is a red herring.

**Comment by zvr** [comment]
I also agree with @bkuhn to add

> instructions for installing modified versions of the supplied software

in the note describing various compliance artifacts in definition 2.1.

I'll skip the "on the target device" for simplicity, same as we only mention "source code" and not "complete corresponding" ;-)

**Comment by bkuhn** [comment]
@zvr wrote:
> I'll skip the "on the target device" 

Yeah, that makes sense to me and seems a reasonable compromise.  But, @ossguy, since it was your phrase, what do you think?

**Comment by ossguy** [comment]
I included "on the target device" because companies often fail to provide a cross-compiler (when necessary) and this phrase makes it more clear that they should.  Also, they sometimes appear to assume that "install" just means copying files into some directory structure, but then stopping short of creating a firmware image that can be loaded onto the device the code was intended for.

However, I'm fine with removing "on the target device" for brevity, as the text preceding it at least hints that the distributor needs to resolve the above issues.

**Comment by MarkGisi** [comment]
I agree section 2.2.1 would be a better fit for @ossguy's recommendation. We want to capture the license obligation concept and not necessarily the exact wording of any given license.  I added the following to the list of items in definition 2.2:
       "build and install scripts"
and now reads as follows:

Note: The collection may include (but is not limited to) one or more of the following: attribution notices, source code, build and install scripts, copy of licenses, copyright notices, modification notifications, written offers, open source component bill of materials, and SPDX documents.

This update was made to draft version rc3 which will be made available by the end of the week.
