### ISSUE TITLE
v2.1 § 3.2.1.1 - assist in resolving compliance issues quickly by sending contact info to orgs

### ISSUE THREAD

**Issue by ossguy** [OpenChain-Project/License-Compliance-Specification#44]
As requested on the OpenChain Project Specification Work Group mailing list, I am submitting the following public comment.  I was unable to add this as a pull request, since I couldn't find the source code for v2.1 (only v2.0 and earlier are at https://github.com/OpenChain-Project/Specification/tree/master/version with no branches aside from master).  If I am looking for the v2.1 source code in the wrong place (i.e. for the https://wiki.linuxfoundation.org/_media/openchain/openchainspec-2.1.draft.pdf document), please let me know.  Anyway, here is the suggestion:

Add to the end of Section 3.2.1.1 (after "Compliance Directory)."): 

"To aid in quickly resolving externally discovered compliance issues, this contact information should also be sent to organizations that check for license compliance, such as the Free Software Foundation (at licensing@fsf.org ) and Software Freedom Conservancy (at compliance@sfconservancy.org )."

It is often the case that organizations doing license compliance work do not know who to contact about compliance issues at a particular company when they receive a report of a compliance issue with that company's compliance artifacts.  If the contact info is provided to them before these issues arise, then they can more quickly find an appropriate contact at the company to ensure that the compliance issue is resolved in a timely manner, rather than going through multiple levels of customer support before they find the right person.

Denver Gingerich
Software Freedom Conservancy

**Comment by MarkGisi** [comment]
It would be outside the scope of the spec to list all the organizations that do compliance work. However, the Linux Foundation's Open Compliance Directory is a place to go to find compliance contact personnel. One of the directory's main objectives is to assist organizations doing compliance work (e.g., Free Software Foundation and Software Freedom Conservancy) when they want to easily locate compliance personnel at a specific organization.

**Comment by ossguy** [comment]
@MarkGisi I wasn't able to find a list of companies that are in the Open Compliance Directory.  All I found was a form to use to request contact info for a specific company (which might or not be in the Directory, but I can't tell since I couldn't find a list).  Could you please point me to the list of companies that are in the Open Compliance Directory?

Whether I consider this ticket to be solved by the Open Compliance Directory depends on the answer to the above question.

**Comment by MarkGisi** [comment]
I do not believe the Directory does not publish the list of all those registered. It allows one to inquire about a specific organization by filling out and submitting a form. I believe this is the spirit of your intent. Of course, an organization may not be listed it the directory. If they are OpenChain conforming they need to make it public.  It is up to an organization to decide how to satisfy that requirement.The directory is one option. Posting an email address on their website is another.

**Comment by shanecoughlan** [comment]
@MarkGisi, I concur. It’s about giving an option for connecting entities and enquiries. Some parties will seek public listings in various locations (including, for instance, their own site), and some parties will prefer to have an avenue for connection such as a contact request form. Both result in a useful channel to address questions and concerns.
