### ISSUE TITLE
v2.1 § 3.3.2 - clarify "modified open source" term to mitigate common compliance error

### ISSUE THREAD

**Issue by ossguy** [OpenChain-Project/License-Compliance-Specification#45]
As requested on the OpenChain Project Specification Work Group mailing list, I am submitting the following public comment.  I was unable to add this as a pull request, since I couldn't find the source code for v2.1 (only v2.0 and earlier are at https://github.com/OpenChain-Project/Specification/tree/master/version with no branches aside from master).  If I am looking for the v2.1 source code in the wrong place (i.e. for the https://wiki.linuxfoundation.org/_media/openchain/openchainspec-2.1.draft.pdf document), please let me know.  Anyway, here is the suggestion:

Replace this text in Section 3.3.2:

"Contains modified open source;"

with the following:

"Contains modified open source (usually the case unless supplied software does not require installation instructions or a specific compiler);"

It is often the case that I find companies indicating they have not modified the open source they distribute, but parts of the source code are missing because their compliance artifacts do not include installation instructions or information on which compiler to use (e.g. if a cross-compiler is required).  Popular copyleft licenses such as GPLv2 say that source code must include "the scripts used to control compilation and installation of the executable" so it is important to remind users who wish to be OpenChain conformant that modifications would normally include any compilation and installation instructions necessary for their supplied software to be properly built and installed on whatever device they are distributing or targeting for installation (if those instructions are not already part of the open source being used).

Denver Gingerich
Software Freedom Conservancy

**Comment by MarkGisi** [comment]
We added "build and install scripts" to the compliance artifacts definition in section 2.1.
