### ISSUE TITLE
mention of "copyleft"

### ISSUE THREAD

**Issue by zvr** [OpenChain-Project/License-Compliance-Specification#48]
In the whole spec, the term "copyleft" is encountered only once: in 3.3.2, one of the use cases for license compliance is:

> Integrated with other open source such that it may trigger _copyleft_ obligations;

We know what that is, but readers/users of the spec may not be experts.
We should either define it in the terms, or eliminate it.
Since it's only once, I'd suggest the latter.

It's only an indicative use case, so we don't need to be extremely accurate; I could see the word being replaced by "source code distribution" or even a generic "license". 

(this was triggered from reading #43, where there was discussion of compliance artifacts of "copyleft" licenses).

**Comment by MarkGisi** [comment]
I agree. fewer new terms makes the spec clearer - especially to first time readers. 
    "copyleft obligations" was replaced with "additional licensing obligations"
in draft version rc3 (to be published by end of week).

It also makes the spec a little more license agnostic which is another design requirement.
