### ISSUE TITLE
Pull-request capable format

### ISSUE THREAD

**Issue by HansMKern** [OpenChain-Project/License-Compliance-Specification#49]
Can you provide the specification V2.1 in a format that allows collaboration, e.g. markdown or asciidoc? 

It would also speedup future activities like further enhance the document or translations.
Thanks.

**Comment by MarkGisi** [comment]
The official specification is maintained in MS Word largely for the ability to maintain a certain formatting structure. This is particularly beneficial for maintaining a certain format for ISO certification.  

Having noting that, if someone wants to create a markdown version, we can use it as a scratch pad text version to allow others to express certain wording changes.

**Comment by stephenkilbaneadi** [comment]
I believe this issue can finally be closed, given that the project has switched to maintaining the specification in Markdown.
