### ISSUE TITLE
Consider updating 4.1.2   to looking for evidence, not an action. (Malcolm Bain)

### ISSUE THREAD

**Issue by MarkGisi** [OpenChain-Project/License-Compliance-Specification#5]
4.1.2   Same as above, we are looking for evidence, not an action. Are we requiring   “Copies of the CA are archived” as evidence (and then “planned to exist”), or   shouldn’t we be requiring some extrinsic evidence that the CA have been archived and that there is a plan to   maintain this archive?  Should it be therefore “4.1.2 A documented   procedure for archiving CA of SS and records that this procedure has been   properly followed”  (see 3.1.2 as a model)
--

**Comment by MarkGisi** [comment]
Good point. Consistency is an important attribute of the spec. Made the following text update:

A documented procedure for archiving copies of the Compliance Artifacts of the Supplied Software - where the archive is planned to exist for at least as long as the Supplied Software is offered or as required by the Identified Licenses (whichever is longer). Records exist that demonstrate the procedure has been properly followed

**Comment by HansMKern** [comment]
You forgot one aspect: legal requirements...

A documented procedure for archiving copies of the Compliance Artifacts of the Supplied Software - where the archive is planned to exist for at least as long as the Supplied Software is offered, or as long as the legal requirements for the product require it, or as required by the Identified Licenses (whichever is longer). Records exist that demonstrate the procedure has been properly followed

Not so elegant anymore, but depending on the product type you have to be able to provide this information up to 25 years after the last product with that software was delivered to the customer. (ask the guys that build commercial aircraft or car manufactures...

**Comment by MarkGisi** [comment]
> You forgot one aspect: legal requirements...

We are solely focused on license compliance requirements and not other potential legal requirements. The objective is to include a time frame that is consistent with open source license obligations. 

As for the products that last a long time (e.g., 25 years), it is a good practice for a software recipient to ensure they obtain the compliance artifacts at the time they receive the software. The recipient can than archive them and is not dependent on the software distributor who may not be required to provide the artifacts after a certain date or they cease to exist.

**Comment by MarkGisi** [comment]
I  update the text to include an additional two year grace period. This still needs to be discussed and agreed upon by the spec working group. 

  "A documented procedure for archiving copies of the Compliance Artifacts of the Supplied Software - where the archive is planned to exist for at least two years past the last offer of the Supplied Software or as required by the Identified Licenses (whichever is longer). Records exist that demonstrate the procedure has been properly followed."

**Comment by HansMKern** [comment]
@MarkGisi could we at least add here a footnote that other legal requirements might require other archiving periods.

The ration behind this: with a long supply chain that hands over OSS from one legal entity to another, the customer has the right to come back and ask for license fulfillment from any supplier that handled the OSS in question. This leads to a huge gap, especially for fast growing software companies that are not aware of their responsibilities 

--> we should open a new issue on this or reopen this one. :-)

**Comment by MarkGisi** [comment]
Re-opening to address the concern of whether we should include addition clarification around the duration of fulfillment. Perhaps we include additional note about other potential legal requirements may exist with respect to record retention.

**Comment by MarkGisi** [comment]
At the Feb 18th Spec Working group meeting there was a general consensus that the spec should mention that artifacts should be retained for some period of time past the last offering. The challenge was agreeing on whether to include a specific minimum duration (e.g., 12 months). One suggestion was to state "for a reasonable period of time" instead of an explicit time. One concern with that approach was some may ask what is a reasonable time. We will need to discuss further what to do.

We also discussed whether the spec should address the need to consider the fact that different countries may have specific document retention requirements. The consensus was that would add unnecessary complexity without adding additional value to the compliance task. The working group still needs to decide whether to specify a minimum time. If a given country has a longer or shorter time period that would not effect the minimum requirement (if we decide to include one). That is, if the local legal requirement is shorter then the spec minimum time would determine the duration. If local legal requirement was longer then the spec minimum  then the spec requirement would be met.

**Comment by shanecoughlan** [comment]
I think both of these may be suitable without being prescriptive:

"for a reasonable period of time"
"for a reasonable period (e.g two years) past the last offer..."

**Comment by HansMKern** [comment]
// first of all: INAL -- I'm Not A Lawyer 

Again, the period of time depends on the legal requirements. And I want to build up awareness that this is a critical topic in the supply chain.

Scenario A1: a software supplier provides software containing open source to its customer. Due to the fact that open source licenses allow the end user to come back to anyone in the supply chain, the supplier should know what commitments he/she did by providing the code. If the customer is an avionic company, that means 25 yrs after last sold plane. So this offers new business models (guaranteed code provisioning up to X years)

So I would not name any time period, I would stick with "for a in business common period (e.g. liability time)"

**Comment by theopenchainproject** [comment]
I think this may bring us back to “a reasonable period of time”, with reasonable determined sector by sector via supplier/customer negotiations. ;)

**Comment by HansMKern** [comment]
reasonable\footnote{determined by domain, legal requirements, customer contracts}

**Comment by MarkGisi** [comment]
footnoted has been added.
