### ISSUE TITLE
Definitions: Program

### ISSUE THREAD

**Issue by MarcelScholze** [OpenChain-Project/License-Compliance-Specification#54]
The "Program" should reflect the "Program Scope" which should be stated in the definition. Otherwise the definition refers to all Open Source license compliance activities of a company.

Suggestion: 

"Program" - the set of policies, processes, and personnel that manage **the** organization's Open Source license compliance activities **in relation to the Program Scope (1.4)**.

**Comment by shanecoughlan** [comment]
Added and closed on Spec 3.0:
https://github.com/OpenChain-Project/License-Compliance-Specification/commit/b87957a9346ad8535c5679cab3b260a3396c67b8
