### ISSUE TITLE
Content and Sorting of '1.0 Program Foundation'

### ISSUE THREAD

**Issue by MarcelScholze** [OpenChain-Project/License-Compliance-Specification#56]
We suggest to resort '1.0 Program Foundation' like:

1.1 Program Scope
1.2 Policy
1.3 Awareness 

Thoughts behind it: We should start with the scope, as this sets the scene and within a company it is then clear for whom/what it is relevant. The policy would reflect the scope and therefore be next.

'1.2 Competence' we suggest to move just before '2.2 Effectively Resourced' at these topics build upon each other.
'1.5 Licence Obligations' we suggest to move to chapter '2.0' as there we are on a task level / management processes where in 1.0 we have the foundation content.

**Comment by shanecoughlan** [comment]
As of 2024-02-20 monthly North America / Asia call format is:

3.1 - Program foundation sub-categories:

Policy
Competence
Awareness
Program scope
License obligations

**Comment by shanecoughlan** [comment]
= This call agreed to reorder the material from =

3.1 - Program foundation

3.1.1 Policy
3.1.2 Competence
3.1.3 Awareness
3.1.4 Program scope
3.1.5 - License obligations

== to this (merged with two sections below) with a placeholder addition to policy for *legal* obligations - including legislation - to be potentially scoped, addressing a concern that senior management may need that at a product level, above the mechanism for license obligation per se == 
(comment from Prasad at Cisco)

3.1 - Program foundation

3.1.1 - Program scope
3.1.2 - Policy  
 + note: A policy may include ...  [ reference to legislation] ... etc. 
3.1.3 - Awareness

3.2 - Relevant tasks defined and supported

3.2.1 - Access
3.2.1 - Competence
3.2.3 - Effectively resourced

3.3 - Open source content review and approval

3.3.1 - Bill of materials
3.3.2 - License obligations
3.3.3 - License compliance

Update merged here:
https://github.com/OpenChain-Project/License-Compliance-Specification/commit/8b5f92986f7f0b9265ccee7950d5c8f56149d2b2
