### ISSUE TITLE
Content of '2.2 Effectively Resourced'

### ISSUE THREAD

**Issue by MarcelScholze** [OpenChain-Project/License-Compliance-Specification#57]
**1st:**

We suggest to combine the 5th bullet of 2.2 and 2.2.5 with '1.5 License Obligations' (which we suggest to move to 2.0 see other #56) as these are rather processes to perform for licence obligations than for 'identify and resource program'.

Move: 
- A process exists for the resolution of Open Source license compliance issues.
2.2.5 A documented procedure for handling the review and remediation of non-compliant cases.
to '1.5 License Obligations'

**2nd:**

We suggest to combine the 3th bullet of 2.2 with '1.1 Policy' as this is rather a process for the policy management than for 'identify and resource program'.

Move:
- A process exists for reviewing and updating the policy and supporting tasks;
to 1.1 Policy

**Comment by shanecoughlan** [comment]
Review on 2024-02-20 North America / Asia monthly call:

@MarcelScholze this issue appears to be out of sync with the current version of the spec (https://github.com/OpenChain-Project/License-Compliance-Specification/blob/master/3.0/en/openchain-license-compliance-3.0.md), so it is being closed here. If you are still concerned about the points contained in this topic and they were not addressed by the updates, please open a new issue highlighting them and they will be addressed in a future monthly call.
