### ISSUE TITLE
Objectives (1.3 vs. 1.4 vs. 1.1)

### ISSUE THREAD

**Issue by MarcelScholze** [OpenChain-Project/License-Compliance-Specification#58]
Within '1.3 Awareness' it is requested to be aware of the '**b) Relevant Open Source objectives**', however they are not mentioned anywhere else within '3) Requirements'.

We suggest to mention 'objectives' in 1.4 Program Scope:
1.4.1 A written statement that clearly defines the scope**, objectives,** and limits of the Program.

and also we suggest to mention 'objectives' in 1.1 Policy
1.1.1 A documented Open Source policy **that reflects the scope, objective, and limits of the Program**.

**Comment by shanecoughlan** [comment]
Change accepted on 2023-10-17 monthly call as:

3.1.1 A documented Open Source policy 
to
3.1.1 A documented Open Source policy that reflects the scope, objectives, and limits of the Program.

3.1.4.1 - A written statement that clearly defines the scope and limits of the program.
to
3.1.4.1 - A written statement that clearly defines the scope, objectives and limits of the program.

**Comment by shanecoughlan** [comment]
Closed after merge here: https://github.com/OpenChain-Project/License-Compliance-Specification/commit/b56853c8c835e1f534895c32fca3a9bd46785a47
