### ISSUE TITLE
Review notes: Version 3.0 OpenChain ISO/IEC 5230:2024 (proposed) - DRAFT 

### ISSUE THREAD

**Issue by andreaskotulla** [OpenChain-Project/License-Compliance-Specification#70]
#1:
It is  suggested to add a "version history", describing the main enhancments/adaptions for each of the versions. Somwhere in the beginning of the document

#2:
3.3.2 
We suggest to add following common use cases in the bullet list:
Contains License exceptions 
Contains Export restrictions

Rationale: Both are very common use cases. 
For export restrictions the standard may, in the future, reference to the work that the "Export control group" is currently working on

**Comment by shanecoughlan** [comment]
As per call 2024-06-18

Point 1 addressed by making old specs available and hosting diff on GitHub, point 2 belongs in reference material rather than spec itself. 

Closing issue with thanks.
