### ISSUE TITLE
[Agenda/Minutes]

### ISSUE THREAD

**Issue by Hawthorne001** [OpenChain-Project/License-Compliance-Specification#73]
----
## yyyy.mm.dd Agenda/Minutes
--- 
Time hh:mm (timezone) - See the time in your [timezone](https://everytimezone.com/s/a8399b00)

- Chair – {Name} (Organisation)
- Vice Chair - {Name} (Organisation)
- Convener/Scribe – {Name} (Organisation)

## Antitrust Policy 
{ Add https://github.com/OpenChain-Project/Reference-Material/tree/master/Anti-Trust-Policy }

### Recordings
WG agreed to record all [Meetings](Link to recording). This meeting recording will be available until the next scheduled meeting

### Roll Call 
Please *add 'Attended'* to this issue during the meeting to denote attendance.

## Agenda 
- [ ] Convene & Roll Call 
- [ ] Approve agenda
- [ ] Approve previous minutes

## Introductions
{round robin of into's}

## Latest news
> Name of person to be entered here

## Discussion item 1
> Name of person to be entered here

## Discussion item 2
> Name of person to be entered here

## Discussion item 3
> Name of person to be entered here

## Next Meeting
- [x] yyyy.mm.dd hh:mm (timezone)

## Adjourn
{Any objections to closing}

**Comment by shanecoughlan** [comment]
Not relevant.
